---
title: "version 1"
output: html_document
date: "2024-10-07"
---


#some steps for commiting to git and pushing to github:
for git use getwd() function to determine pathway 
cd /home/robmcneil/Desktop/test
git branch
git checkout your-branch-name (can do this in R terminal )
git status
git push origin your-branch-name
#prof mentioned inclusion of an interaction term 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


test
```{r}

#read in data

library(tidyverse)
library(dplyr)
library(lme4)
library(ggplot2)
library(VIM)
library(naniar)
library(readr)
library(kableExtra)
library(finalfit)
library(broom)
library(sjPlot)
library(StepReg)
library(reshape2)
library(Amelia)

#linux pathway
hiv<- read_csv("/home/robmcneil/Documents/advanced_data/hiv_dataset.csv")

#windows pathway
#hiv<- read_csv("C:/Users/rrm10/OneDrive/Desktop/advanced data analysis/hiv_dataset.csv")


#check data types
str(hiv)

```



```{r}
#filter dataset to two years
hiv_filtered <- hiv %>%
  filter(years <= 2, hivpos ==1)


#add labels 

# add labels to hard drugs
#hiv_filtered <- hiv_filtered %>%
    #mutate(hard_drugs = case_when(
       # hard_drugs == "Never Used" ~ 0,
       # hard_drugs == "Current Users" ~ 1,
       # hard_drugs == "Previous Users" ~ 2,
      #  TRUE ~ NA_real_  # Handling any other cases
  #  ))
```


```{r}
#visualize CD4 positive cells

#test assumption of linearity 
#dont need to test for linearity with categorical variables 
#good graph for presentation 
ggplot(hiv_filtered, aes(x = factor(hard_drugs), y = LEU3N, color = factor(hard_drugs))) +
  geom_boxplot() +
  stat_summary(fun = mean, geom = "point", shape = 3, size = 3, color = "black") +  # Adds mean points
  labs(
    title = "Figure Box Plot of CD4 based on Drug Usage Groups",
    x = "Drug Usage Group",
    y = "CD4",
    color = "Treatment Group"
  ) +
  theme_minimal()
```


```{r}

#for viral load outcome
#dont need to test for linearity with categorical variables 
#good graph for presentation 
ggplot(hiv_filtered, aes(x = factor(hard_drugs), y = VLOAD, color = factor(hard_drugs))) +
  geom_boxplot() +
  stat_summary(fun = mean, geom = "point", shape = 3, size = 3, color = "black") +  # Adds mean points
  labs(
    title = "Figure Box Plot of CD4 based on Drug Usage Groups",
    x = "Drug Usage Group",
    y = "Viral Load",
    color = "Treatment Group"
  ) +
  theme_minimal()




```

```{r}

#create correlation matrix 

hiv_filtered_c <- hiv_filtered %>%
  na.omit()
correlation_matrix <-cor(hiv_filtered_c)
print(correlation_matrix)
#heropialte (took heroine or opiates since last visit) and IDU (took drugs with a needle) are highly correlated with hard_drugs



```






```{r}

#simple linear regression for CD4 + tcell count

lm_LEU3N <- lm(LEU3N ~ hard_drugs, data = hiv_filtered)
summary(lm_result)

#slr for viral load 

lm_vload <- lm(VLOAD ~ hard_drugs, data= hiv_filtered)
summary(lm_vload)

#need to include confidence intervals
```

```{r}

#calculate residuals and fitted values, of my models 

LEU3N_fitted<- predict(lm_result)
LEU3N_resid <-  resid(lm_result)

vload_fitted <- predict(lm_vload)
vload_resid <- resid(lm_vload)

 


```


```{r}

# Plot Residuals vs Fitted LEU3N  (Homoscedasticity)
ggplot(data = NULL, aes(x = LEU3N_fitted, y = LEU3N_resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Figure 1: CD4 T-cells Residuals vs Fitted", 
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()



#plot residuals vs fitted for Viral Load
ggplot(data = NULL, aes(x = vload_fitted, y = vload_resid)) +
  geom_point() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Figure 2: Viral load Residuals vs Fitted", 
       x = "Fitted Values",
       y = "Residuals") +
  theme_minimal()

```


```{r}


# Fit the MANOVA model
manova_model <- manova(cbind(LEU3N, VLOAD) ~ hard_drugs, data = hiv_filtered)

# Summarize the MANOVA model
summary(manova_model)


summary(manova_model, test = "Pillai") 

```




```{r}
#perform stepwise regression for model selection 
# Remove rows with NA values in the relevant columns
hiv_clean <- hiv_filtered %>%
  na.omit

# Define the formula for LEU3N (saturated)
LEU3N_formula <- LEU3N ~ hard_drugs + IDU+HEROPIATE+ age + EDUCBAS + RACE + ADH +DKGRP + SMOKE + CESD + DYSLIP +LDL +TRIG+ TCHOL +FP+FRP+KID+LIV34+DIAB+HBP+BMI+income+HASHF

# Perform stepwise regression for attachment on the cleaned data
stepwise_model <- stepwise(formula = LEU3N_formula,
                                   data = hiv_clean,
                                   type = "linear",
                                   include = c('hard_drugs'), # Adjust as needed
                                   strategy = "bidirection",
                                   metric = c("AIC", "BIC"))

# view stepwise model
stepwise_model


```




